[PL] Partial translation
osuTitanic/wiki pull request #16
Opened 2024-08-01 08:18 UTC by Zordon1337

As title says, i've partially translated wiki to polish, unfortunately i skipped 
People->BAT
Ranking Criteria
Because i have no clue how to translate them especially the Ranking Criteria part
rest is fully translated

2024-08-26 07:00 UTC, Zordon1337 commented
Hello?

2024-08-26 07:03 UTC, Lekuruu commented
Hi

2024-08-26 07:10 UTC, Zordon1337 commented
> Hi

When review :troll_face:

2024-08-26 07:12 UTC, Lekuruu commented
When u finish it + when I learn polish

2024-08-26 07:15 UTC, Zordon1337 commented
Okay cya in 420 years 😀😀😀😀😀😀😀😀😀😀😀

pon., 26 sie 2024, 09:13 użytkownik Levi ***@***.***> napisał:

> When u finish it + when I learn polish
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/osuTitanic/wiki/pull/16#issuecomment-2309500688>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APQYMOPL3GLD2XDR3NH5CS3ZTLIQ3AVCNFSM6AAAAABL2BBM6WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMBZGUYDANRYHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-06 22:33 UTC, BlueChinchompa commented
polska gurom

also we should probably make a page at some point talking about translation and how we should go about approving that. (I totally wont forget about this tomorrow)

2024-10-06 22:41 UTC, Zordon1337 commented
o shit i forgot about this one

2024-10-20 23:34 UTC, BlueChinchompa commented
o shit

2024-10-21 04:54 UTC, Zordon1337 commented
I wonder if my translation got already outdated

2024-10-21 05:52 UTC, iSlodinxOsu requested changes

2024-10-21 05:52 UTC, iSlodinxOsu commented on wiki/People/Administrators/pl.md
> +## Current Members
You need to translate this

2024-10-21 05:54 UTC, iSlodinxOsu requested changes

2024-10-21 05:54 UTC, iSlodinxOsu commented on wiki/Installation/pl.md
> +Jest szansa na to że Windows Defender zablokuje plik z osu, ponieważ plik gry nie jest podpisany cyfrowo (Takie podpisanie by kosztowało nas 200$).
```suggestion
Jest szansa na to że Windows Defender zablokuje plik z osu!, ponieważ plik gry nie jest podpisany cyfrowo (Takie podpisanie by kosztowało nas 200$).
```

2024-10-21 05:54 UTC, iSlodinxOsu commented on wiki/People/Administrators/pl.md
> +[Adachi](https://osu.titanic.sh/u/39)          | Menadżer Społecznościowy i Deweloper systemu PP
```suggestion
[Adachi](https://osu.titanic.sh/u/39)          | Menadżer Społecznościowy i Deweloper systemu pp
```

2024-10-21 05:54 UTC, iSlodinxOsu commented on wiki/Rules/pl.md
> +3. **Bądz miły dla innych.** Jakiekolwiek zastraszanie, raszim, lub antagonizm nie ma miejsca tutaj na Titanic'u! To jest poprostu serwer o klikaniu kółek, łapaniu owoców, uderzania bębny, i rozwalan
```suggestion
3. **Bądz miły dla innych.** Jakiekolwiek zastraszanie, raszim, lub antagonizm nie ma miejsca tutaj na Titanic'u! To jest poprostu serwer o klikaniu kółek, łapaniu owoców, uderzania bębny, i rozwalaniu klawiatury podczas udawania że jesteś Cookiezi'm i graniu starych map, nie żeby być dupkiem wobec innych.
```

2024-10-25 08:00 UTC, Zordon1337 commented
Maybe today

2024-11-04 15:44 UTC, iSlodinxOsu commented
By the way, just to remind you to update your PR, due to these changes in https://github.com/osuTitanic/wiki/pull/33/

2024-11-16 16:18 UTC, Lekuruu commented
I'd close this for now. @Zordon1337 if you get time again for a translation, please make a pr again, since a lot of pages have been updated.

2024-11-16 16:18 UTC, closed without merging