Add `Media_managers` page
osuTitanic/wiki pull request #29
Opened 2024-10-21 00:41 UTC by BlueChinchompa

2024-10-21 06:03 UTC, iSlodinxOsu requested changes

2024-10-21 06:03 UTC, iSlodinxOsu commented on wiki/People/Media_managers/en.md
> +## Media manager
```suggestion
## Media managers
```

2024-10-21 06:03 UTC, iSlodinxOsu commented on wiki/People/Media_managers/en.md
> +Currently this is only one Media manager.
I think it's kinda weird to read this, probably should just remove that.

2024-10-21 06:05 UTC, iSlodinxOsu reviewed
I feel like there is more social medias out there, i might be wrong at this point, i've heard there is mastodon profile aswell.

2024-10-21 14:51 UTC, Lekuruu commented
I think "People" should be more than one person to actually make sense here. We can add a note in the "Admins" list that you manage social media stuff.

2024-10-21 14:52 UTC, Lekuruu commented
Seems like its in here already: https://github.com/osuTitanic/wiki/blob/main/wiki/People/Administrators/en.md

2024-10-22 22:44 UTC, iSlodinxOsu commented
> Seems like its in here already: https://github.com/osuTitanic/wiki/blob/main/wiki/People/Administrators/en.md

i think he got the point though, it's already mentioned in the article.

2024-10-22 23:59 UTC, BlueChinchompa commented
I mostly made this to future proof incase we would want another media manager

> I think it's kinda weird to read this, probably should just remove that.

I agree we could remove that

2024-10-24 07:21 UTC, iSlodinxOsu commented
> Can we convert this into a draft?

Sure, as requested.

2024-10-26 01:16 UTC, BlueChinchompa reviewed
:+1:

2024-10-26 01:32 UTC, iSlodinxOsu requested changes

2024-10-26 01:32 UTC, iSlodinxOsu commented on wiki/People/Media_managers/en.md
> +Media managers are responsible for creating content and maintaing [[Titanic's social media accounts]].
```suggestion
Media managers are responsible for creating content and maintaining [[Titanic's social media accounts]].
```

2025-01-03 18:56 UTC, iSlodinxOsu commented
hmmm? still draft?

2025-02-21 03:40 UTC, iSlodinxOsu requested changes
Some improvements i think?

2025-02-21 03:40 UTC, iSlodinxOsu commented on wiki/People/Media_managers/en.md
> +Media managers are responsible for uploading scores to the Titanic! [Youtube](https://www.youtube.com/@osuTitanic) and [Bitview](https://www.bitview.net/user/osuTitanic). As well as also posting upda
```suggestion
Media managers are responsible for uploading videos on [YouTube channel](https://www.youtube.com/@osuTitanic) and [BitView channel](https://www.bitview.net/user/osuTitanic) as well as also posting updates on [BlueSky](https://bsky.app/profile/titanic.sh) and [Twitter](https://x.com/osutitanic) accounts.
```

2025-07-10 20:30 UTC, closed without merging