Create `Testers` page
osuTitanic/wiki pull request #37
Opened 2024-11-13 17:52 UTC by BlueChinchompa

I don't have the dates when people became testers so @Lekuruu is probably going to have to help with that.

Also @Meruru-chan can make a commit and add when they became a tester.

2024-11-14 07:23 UTC, iSlodinxOsu requested changes
Does this mean that they also find bugs on clients aswell?

2024-11-14 07:23 UTC, iSlodinxOsu commented on wiki/People/Testers/en.md
> +Testers are people who have helped test out clients and features on Titanic!
```suggestion
Testers are users who have helped test out clients and features on Titanic!
```

2024-11-14 09:33 UTC, Lekuruu commented
They technically are "playtesters" as soon as they registered, so I'd use that

2024-11-14 11:16 UTC, iSlodinxOsu commented
> They technically are "playtesters" as soon as they registered, so I'd use that

Do you agree by replacing N/A to "Since the Beginning"?

2024-11-14 12:03 UTC, Lekuruu commented
Uhhh, I don't see a reason why using the registration date would be harder

2024-11-14 13:23 UTC, BlueChinchompa commented
> They technically are "playtesters" as soon as they registered, so I'd use that

Im assuming people like rory or crazy were testers since they joined then right?

2024-12-05 23:47 UTC, iSlodinxOsu commented
any progress?

2024-12-06 12:00 UTC, BlueChinchompa commented
> any progress?

I just added the dates for Natasha and CrazyCSIW6

2024-12-13 13:22 UTC, BlueChinchompa commented
Okay this should be ready to be merged now

2024-12-13 13:26 UTC, iSlodinxOsu approved these changes

2024-12-13 13:27 UTC, iSlodinxOsu requested changes

2024-12-13 13:27 UTC, iSlodinxOsu commented on wiki/People/Testers/en.md
> +[Meru](https://osu.titanic.sh/u/41) | September 17th 2023
```suggestion
[Meru](https://osu.titanic.sh/u/41) | September 17th, 2023
```

2024-12-13 13:27 UTC, iSlodinxOsu approved these changes

2024-12-13 13:30 UTC, Meruru-chan approved these changes
w

2024-12-13 13:31 UTC, merged